FROM node:18-alpine as base

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn

COPY . .

RUN yarn nx build user-wed --configuration=production

FROM node:18-alpine as runner

WORKDIR /app


COPY package.json yarn.lock ./

RUN yarn

COPY --from=base app/dist/apps/user-wed ./

EXPOSE 4201

CMD ["yarn", "start"]