FROM node:18-alpine as base

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn

COPY . .

RUN yarn nx build user-wed --configuration=production

FROM node:18-alpine as runner

WORKDIR /app


COPY package.json yarn.lock ./

RUN yarn

COPY --from=base /app/user-web/build/production ./

EXPOSE 4201

RUN ["yarn", "nx", "sever", "user-wed", "--configuration=production"]